/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Pane: typeof import('./src/components/SplitPane/pane.vue')['default']
    Resizer: typeof import('./src/components/SplitPane/resizer.vue')['default']
    SplitPane: typeof import('./src/components/SplitPane/index.vue')['default']
  }
}
