name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://github.com/eastgold15/vue-split-pane-v3.git'
    
    - name: Setup pnpm
      uses: pnpm/actions-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run : pnpm install

    - name: Build
      run: pnpm run build 
    
    - name: Publish to npm 
      run : pnpm  publish --no-git-checks 
      env :
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}

    - name: create github release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

